version: "3"

services:
  mongo:
    image: mongo
    container_name: "Mongo_DB_Movie_Webb_App"
    restart: unless-stopped
    ports:
      - 27028:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: s3cr37

  mongo-express:
    image: mongo-express
    container_name: "Mongo_DB_Express_Movie_Web_App"
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: s3cr37
